### ISSUE TITLE
stela.proto is out of date ?

### ISSUE THREAD

**Issue by vanloswang** [forestgiant/stela#4]
I add a rpc func and use protoc 3.4 to compile stela.proto to generate stela.pb.go with following commad:
```
protoc --go_out=. *.proto
```
The generated stela.pb.go is mising GetName,GetHostname,GetIPv4,GetIPv6,GetPort,GetPriority and so on. 
Is stela.proto out of date? So how to generate the right stela.pb.go ?

**Comment by jesselucas** [comment]
I believe you need to pass the grpc plugin to the protoc tool:
`protoc --go_out=plugins=grpc:. *.proto`

The protoc tool is still a bit of a mystery to me 🙀. Here's the command we run internally: https://gist.github.com/jesselucas/c8463ceed6ca73e8c5a693e1c54c0dc0

I'm using version `libprotoc 3.1.0`

**Comment by vanloswang** [comment]
@jesselucas Thank you very much. It's ok now. protoc 3.4 also works  for me.
